# Generated by Django 3.2.6 on 2022-05-21 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('product_type', models.CharField(max_length=20)),
                ('GST', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_type', models.CharField(max_length=20)),
                ('dop', models.DateField()),
                ('temp', models.CharField(max_length=100)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('Department', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=20)),
                ('line_manager', models.CharField(max_length=20)),
                ('doj', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
