# Generated by Django 3.2.6 on 2022-05-25 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0003_allocation_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation_approval',
            old_name='allocated_date',
            new_name='request_date',
        ),
        migrations.RemoveField(
            model_name='allocation_approval',
            name='id',
        ),
        migrations.AddField(
            model_name='allocation_approval',
            name='all_req',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='aid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
