# Generated by Django 3.2.6 on 2022-05-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20220525_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation_approval',
            name='reason',
            field=models.IntegerField(),
        ),
    ]
